### ISSUE TITLE
Replaces favcions when they already exist

### ISSUE THREAD

**Issue by LonMcGregor** [LonMcGregor/replace-favicon#3]
Example:

https://vivaldi.com/fr/blog/teamblog/spinner-during-page-load-vivaldi-browser-snapshot-1435-4/

Already has a favicon but the extension overwrites it. Figure out why.

**Comment by LonMcGregor** [comment]
This page doesn't have a favicon `<link>`

**Comment by Cqoicebordel** [comment]
Sure. But the issue is that the extension look at https://vivaldi.com/fr/blog/snapshots/spinner-during-page-load-vivaldi-browser-snapshot-1435-4/favicon.ico for the icon when https://vivaldi.com/favicon.ico contains it.

https://github.com/LonMcGregor/replace-favicon/blob/39b64f05f6db1083a5a3a848140f5ffd249cbfbd/src/contentscript.js#L37 is the culprit. It fetches the favicons at the end of the current page.

**Comment by LonMcGregor** [comment]
good find. It will also fail if the favicon is a .png or .gif instead of a .ico

**Comment by Cqoicebordel** [comment]
Confirmed fixed, on Vivaldi.com and on another site.
